# Generated by Django 4.1.6 on 2023-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="نام پوستر")),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات پوستر"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home/poster",
                        verbose_name="عکس پوستر ",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پوستر",
                "verbose_name_plural": "تنظیمات قسمت پوستر",
                "ordering": ("-created",),
            },
        ),
    ]
