# Generated by Django 4.1.6 on 2023-02-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "verbose_name": "ادرس",
                "verbose_name_plural": "تنظیمات قسمت ادرس",
            },
        ),
    ]
