# Generated by Django 4.1.6 on 2023-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_cart",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="شماره کارت"
                    ),
                ),
                (
                    "owner_of_cart",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام دارنده ی کارت",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pay/image",
                        verbose_name="عکس پرداخت موفق",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات حساب برای پرداخت",
                "verbose_name_plural": "تنظیمات قسمت اطلاعات حساب برای پرداخت ها",
            },
        ),
    ]
