# Generated by Django 4.1.6 on 2023-02-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل کاربر",
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شماره تلفن کاربر"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name=" موضوع "
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name=" پیام "),
                ),
                (
                    "status",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name=" ایا چک شده است ؟ ",
                    ),
                ),
                (
                    "is_Accept_terms",
                    models.BooleanField(default=False, verbose_name="پذیرفتن شرایط"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تنظیمات قسمت تماس با ما",
                "ordering": ("-created",),
            },
        ),
    ]
