# Generated by Django 4.1.6 on 2023-02-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contactus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactUs",
            new_name="ContactUsModels",
        ),
    ]
