# Generated by Django 4.1.6 on 2023-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactus", "0003_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="تلفن محل کار"
            ),
        ),
    ]
