# Generated by Django 4.1.6 on 2023-02-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                to="shop.category", verbose_name="دسته بندی محصول"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="shop.tags", verbose_name="برچسب"),
        ),
    ]
