# Generated by Django 4.1.6 on 2023-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_category_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(
                default=False, verbose_name="ایا کالای حراج است ؟"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="special",
            field=models.BooleanField(
                default=False, verbose_name="ایا کالا ویژه است ؟"
            ),
        ),
    ]
