# Generated by Django 4.1.6 on 2023-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_on_sale_product_special"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.AddField(
            model_name="category",
            name="fontasswoem",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="عکس دسته بندی"
            ),
        ),
    ]
