# Generated by Django 4.1.6 on 2023-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_category_image_category_fontasswoem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="english_title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="نام اینگلیسی کالا"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="shop.category",
                verbose_name="دسته بندی محصول",
            ),
        ),
    ]
