# Generated by Django 4.1.6 on 2023-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_english_title_product_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات بیشتر"),
        ),
    ]
