# Generated by Django 4.1.6 on 2023-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop/products",
                verbose_name="1عکس کالا",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop/products",
                verbose_name="2عکس کالا",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop/products",
                verbose_name="3عکس کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop/products",
                verbose_name="عکس کالا اصلی",
            ),
        ),
    ]
