# Generated by Django 4.1.6 on 2023-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_image1_product_image2_product_image3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tip1",
            field=models.CharField(
                blank=True, max_length=12000, null=True, verbose_name="نکته1"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tip2",
            field=models.CharField(
                blank=True, max_length=12000, null=True, verbose_name="نکته2"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tip3",
            field=models.CharField(
                blank=True, max_length=12000, null=True, verbose_name="نکته3"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tip4",
            field=models.CharField(
                blank=True, max_length=12000, null=True, verbose_name="نکته4"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tip5",
            field=models.CharField(
                blank=True, max_length=12000, null=True, verbose_name="نکته5"
            ),
        ),
    ]
