# Generated by Django 4.1.6 on 2023-02-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_like_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="shop.product",
                verbose_name="کالا ها",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="shop.product",
                verbose_name="کالا ها",
            ),
        ),
    ]
