# Generated by Django 4.1.6 on 2023-02-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_comments_products_alter_like_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created",),
                "verbose_name": "محصولات",
                "verbose_name_plural": "تنظیمات قسمت محصولات",
            },
        ),
    ]
