# Generated by Django 4.1.5 on 2023-03-10 18:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_notificationpersonal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discription_of_acceptterms",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        null=True,
                        verbose_name="توضیحات درباره ی شرایط سایت",
                    ),
                ),
                (
                    "target_of_acceptterms1",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 1 از گذاشتن شرایط و ...",
                    ),
                ),
                (
                    "target_of_acceptterms2",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 2 از گذاشتن شرایط و ...",
                    ),
                ),
                (
                    "target_of_acceptterms3",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 3 از گذاشتن شرایط و ...",
                    ),
                ),
                (
                    "target_of_acceptterms4",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 4 از گذاشتن شرایط و ...",
                    ),
                ),
                (
                    "target_of_acceptterms5",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 5 از گذاشتن شرایط و ...",
                    ),
                ),
                (
                    "target_of_acceptterms6",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="هدف شماره 6 از گذاشتن شرایط و ...",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرایط و ضوابط",
                "verbose_name_plural": "تنظیمات شرایط و ضوابط",
            },
        ),
        migrations.AlterField(
            model_name="comments",
            name="message",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="نظرات"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="متن اعلان"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpersonal",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="متن اعلان"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="توضیحات بیشتر"
            ),
        ),
    ]
