# Generated by Django 4.1.5 on 2023-03-10 21:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0016_rename_acceptterms_accepttermsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_shop",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="درباره فروشگاه"
                    ),
                ),
                (
                    "image1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="about/image",
                        verbose_name="عکس 1 فروشگاه",
                    ),
                ),
                (
                    "image2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="about/image",
                        verbose_name="عکس 2 فروشگاه",
                    ),
                ),
                (
                    "image3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="about/image",
                        verbose_name="عکس 3 فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره فروشگاه",
                "verbose_name_plural": "تنظیمات درباره ی فروشگاه",
            },
        ),
        migrations.CreateModel(
            name="PropertyShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fontasswoem",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="عکس بصورت فونت اسم(توضیح داده شده.)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="اسم ویژگی"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="توضیحاتی درباره ی ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی ها",
                "verbose_name_plural": "تنظیمات  ویژگی ها ",
            },
        ),
        migrations.CreateModel(
            name="PosterAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posters",
                        to="shop.product",
                        verbose_name="انتخاب کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "پوستر",
                "verbose_name_plural": "تنظیمات پوستر درباره ما ",
            },
        ),
    ]
