# Generated by Django 4.1.5 on 2023-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_posterabout_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyshop",
            name="fontasswoem",
        ),
        migrations.AddField(
            model_name="propertyshop",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="about/image", verbose_name="عکس"
            ),
        ),
    ]
