# Generated by Django 4.1.5 on 2023-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_remove_propertyshop_fontasswoem_propertyshop_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyshop",
            name="image",
        ),
        migrations.AddField(
            model_name="propertyshop",
            name="fontasswoem",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="عکس بصورت فونت اسم(توضیح داده شده.)",
            ),
        ),
    ]
