# Generated by Django 4.1.6 on 2023-02-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "ثبت درخواست خرید",
                "verbose_name_plural": "تنظیمات قسمت ثبت درخواست خرید ها",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "پایان ثبت درخواست خرید",
                "verbose_name_plural": "تنظیمات قسمت  پیان ثبت درخواست خرید ها",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.AlterField(
            model_name="order",
            name="is_pay",
            field=models.BooleanField(
                default=False, verbose_name="ایا پرداخت شده است ؟"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.order",
                verbose_name="کالا درحال انجام",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.SmallIntegerField(verbose_name="تعداد"),
        ),
    ]
