# Generated by Django 4.1.6 on 2023-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
