# Generated by Django 4.1.6 on 2023-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_discountcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="نام کد تخفیف"
            ),
        ),
    ]
