# Generated by Django 4.1.6 on 2023-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_order_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="addresses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
