# Generated by Django 4.1.6 on 2023-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_remove_order_address_order_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image_payed",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pay/image",
                verbose_name="عکس پرداخت موفق",
            ),
        ),
    ]
