# Generated by Django 4.1.6 on 2023-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_order_image_payed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="DeliveryDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="addresses",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس کاربر"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0, verbose_name="قیمت کلی"),
        ),
    ]
