# Generated by Django 4.1.5 on 2023-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_order_deliverydate_alter_order_addresses_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "پایان ثبت درخواست خرید",
                "verbose_name_plural": "تنظیمات قسمت  پایان ثبت درخواست خرید ها",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="DeliveryDate",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تحویل محصول"
            ),
        ),
    ]
