# Generated by Django 4.1.5 on 2023-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_send", "0002_remove_smssend_user_smssend_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smssend",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="کاربر"
            ),
        ),
    ]
